---
title: "My interactive Rmd!"
author: "Nicole Schmidt"
date: "1/30/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)
library(shiny)

```

```{r flippers,echo= FALSE}

inputPanel(
  
  selectInput(inputId = "pick_spp",
              label = "Pick your penguin species:",
              choices = c("Adélie" = "Adelie", "Cool Chinstrap" = "Chinstrap", "Gentoo"),#first name before = is the name
            selected = "Gentoo"), #tells the app to select gentoo
  sliderInput(inputId = "pt_size",
              label = "Set your point size:",
              min = 1,
              max = 10,
              step = 0.5,
              value = 5) # starting point 
)

penguin_set <- reactive({  # reactive data frame
  penguins %>% 
    filter(species == input$pick_spp) # match the widget from pick_spp
})    

renderPlot({ 
  
  ggplot(data = penguin_set(), aes(flipper_length_mm, y = body_mass_g))+
    geom_point(size = input$pt_size) #input is from the x
  
})

```

